### ISSUE TITLE
Excellent Job! Can you provide some effective re-implemented codes based on DL?

### ISSUE THREAD

**Issue by LiuzhuForFun** [JimmyChame/The-State-of-the-Art-in-HDR-Deghosting#1]
Thanks for your survey!

But I cannot find the DL-based original implementations, such as AHDRNet, Non-local HDR. These results are not similar with the paper reported.

Can you provide the HDR fusion implementations, which can be as baseline?

**Comment by JimmyChame** [comment]
The implementation of AHDRNet have been updated in the list. The author's code of Non-local HDR is not released. The unofficial implementation of Non-local HDR can be found here: [Non-local HDR](https://github.com/tuvovan/NHDRRNet#running)
